name: CI

on:
    push:

jobs:
    build:
        runs-on: windows-11
        steps:
            - uses: actions/checkout@7

            - uses: actions/setup-node@7
              with:
                node-version: 24.13.1

            - run: npm ci

            - run: npm run build

            - uses: actions/upload-artifact@v7
              with:
                path: dist/
    test:
        matrix:
            node: [20,22,24]
            os: [ubuntu-20,windows-11]
        runs-on: ${{matrix.os}}

